export const {
  AWS_ACCESS_KEY_ID,
  AWS_S3_BUCKET_NAME,
  AWS_REGION,
  AWS_SECRET_ACCESS_KEY,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  NEXT_PUBLIC_APP_URL,
  NODE_ENV,
  REDIS_URL,
  NEXTAUTH_SECRET
} = process.env
